version: "3"

services:
  comfyui:
    image: us-central1-docker.pkg.dev/comfyui-demo/comfyui-backend-api/comfyui-backend-api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8188:8188"
    environment:
      LOG_LEVEL: "debug"